### ISSUE TITLE
Endpoint URLs are being passed to JS as objects

### ISSUE THREAD

**Issue by jacksleight** [tv2regionerne/statamic-passport#3] opened 2024-05-21 13:26 UTC
> In the Statamic Passport UI, when I enter details of the access client and click save, nothing happens. The modal stays open and appears unsaved.
>
> I can see from the console that clicking the save button makes an ajax post to "/cp/[object%20Object]/clients" which then times out.

**Comment by SylvesterDamgaard** [comment] 2024-05-21 14:23
Could you try and the this in your passport.php and see if that works?
The issue seems to be a path/url conflict with something else oauth related.

```php
'path' => 'passport',
```

**Comment by steveparks** [comment] 2024-05-21 14:40
@SylvesterDamgaard I was the original poster in the Statamic Discord, and I can confirm that what you suggest above has worked.

I saw that optional setting mentioned in the documentation for this addon, but as I have oauth set to false in /config/statamic/oauth.php 
``` 'enabled' => env('STATAMIC_OAUTH_ENABLED', false), ```
I skipped it, as the docs said it was only needed if I wanted to set that to true.

So I'm not sure where else the OAuth related conflict could be happening. 

Thanks very much for your help

**Comment by SylvesterDamgaard** [comment] 2024-05-21 14:42
@steveparks I will investigate what the reason for it is. Nothing should conflict, but I guess something have changed in core. :)

**Comment by steveparks** [comment] 2024-05-21 14:44
It may also simply be me doing something wrong with my local environment, as I'm very new to Laravel and Statamic!

**Comment by steveparks** [comment] 2024-05-21 14:46
That now works for creating OAuth Clients in the UI... but I'm now hitting an error with creating tokens:

``` LOG.error: Call to undefined method Statamic\Auth\File\User::createToken() ```

(and feel free to tell me to take this elsewhere if it's too far offtopic for this thread)

**Comment by SylvesterDamgaard** [comment] 2024-05-21 14:48
That error is due to a missing HasApiTokens trait in your app/Models/User.php file.  
It should be covered in the Passort documentation here: https://laravel.com/docs/11.x/passport#installation

**Comment by steveparks** [comment] 2024-05-21 14:56
I _think_ I followed that bit correctly.

Here's the top of my app/Models/User.php:

```

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Passport\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

```


(thanks so much for helping)

**Comment by SylvesterDamgaard** [comment] 2024-05-21 15:00
You are right. It seems like you still use the file based user authentication.
Try to follow this guide for switching to database.

https://statamic.dev/tips/storing-users-in-a-database#from-a-fresh-statamic-project

**Comment by steveparks** [comment] 2024-05-21 15:14
Ah yes I do. I was staying file based until some need required moving to database - and I guess now is that time! :)

Thanks for all your help - and for these vitally useful addons

**Comment by SylvesterDamgaard** [comment] 2024-05-21 15:15
No problem. I will let you know as soon as I have looked at the url stuff. :)

**Closed** 2024-05-21 15:42 UTC
